[package]
name = "indexer-management-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-graphql = "7.0"
axum.workspace = true
bigdecimal = { workspace = true, features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
indexer-agent = { path = "../indexer-agent" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
test-assets = { path = "../test-assets" }
thegraph-core.workspace = true
