[package]
name = "indexer-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0", features = [
    "provider-http",
    "network",
    "sol-types",
    "signers",
    "signer-local",
] }
anyhow.workspace = true
bigdecimal = { workspace = true, features = ["serde"] }
bip39.workspace = true
chrono = { version = "0.4", features = ["serde"] }
indexer-attestation = { path = "../attestation" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sqlx.workspace = true
thegraph-core.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
